### ISSUE TITLE
Remove or setup properly MarkdownSnippets.MsBuild?

### ISSUE THREAD

**Issue by sungam3r** [destructurama/attributed#73]
Every time I build solution this package modifies README.md removing changes added in previous commits.

I have never used this package and other repos in destructurama org do not install it.

ping @SimonCropp

**Comment by sungam3r** [comment]
I've got build error
![изображение](https://github.com/destructurama/attributed/assets/21261007/c5913a89-c320-4b13-a175-b58d3e9cd6b8)
For now I disable this package.

**Comment by SimonCropp** [comment]
markdownsnippets works by extracting snippets from cs files and merging them into markdown files. meaning snippets are always correct, and stay in sync with the code

if u want to change the snippets in the md file. u need to change the cs files  where those snippets exist

you are getting a line too long error because longer code lines do not render well with the wrapping when in browsers. especially on mobile devices
u can change the max line length https://github.com/SimonCropp/MarkdownSnippets/blob/main/docs/max-width.md

**Comment by sungam3r** [comment]
Thanks. Fixed in https://github.com/destructurama/attributed/commit/44714d979b5f6686744317c29af14057bcce42ed
